name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: DeLaGuardo/setup-clojure@12.3
      with:
        cli: 1.10.1.693              # Clojure CLI based on tools.deps    
    - name: Run tests
      run: clj -M:test
